name: Tester

on:
  schedule:
    - cron: '0 10 * * 5'  # Every Friday 6:00 AM EST (14:00 UTC)
  workflow_dispatch:

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb  # Install X virtual framebuffer
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run script with virtual display
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
        run: xvfb-run -a python events_emailer.py
